env_files = [
    { path = ".env" },
]

env_scripts = [
    '''
    #!/usr/bin/env bash
    echo "--- Using Environments -----------------"
    echo "AWS_PROFILE      = $AWS_PROFILE"
    echo "----------------------------------------"
    '''
]

[config]
default_to_workspace = false

[tasks.build]
description = "build lambda functions"
command = "cargo"
args = ["lambda", "build", "--release"]

[tasks.deploy]
description = "cdk deploy"
script = '''
#!/usr/bin/env bash
cd cdk
pnpm cdk deploy
'''

[tasks.fmt]
install_script = ['''
#!/usr/bin/env bash
rustup which rustfmt --toolchain nightly
if [ $? -ne 0 ]; then
  rustup install nightly
fi
''']
script = '''
#!/usr/bin/env bash
cargo +nightly fmt
'''

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
  "nextest", "--help",
] }
command = "cargo"
args = [
  "nextest", "run", "--workspace",
  "--status-level", "all", "--test-threads=1",
]

[tasks.clippy-ci]
command = "cargo"
args = ["clippy", "--", "--no-deps", "-Dwarnings"]

[tasks.test-ci]
run_task = "test"
