[config]
default_to_workspace = false

[tasks.build]
description = "build lambda functions"
command = "cargo"
args = ["lambda", "build", "--release"]

[tasks.lint-cdk]
script = '''
#!/usr/bin/env bash
cd cdk
pnpm lint
'''

[tasks.fmt]
install_script = ['''
#!/usr/bin/env bash
rustup which rustfmt --toolchain nightly
if [ $? -ne 0 ]; then
  rustup install nightly
fi
''']
script = '''
#!/usr/bin/env bash
cargo +nightly fmt
cd cdk
pnpm fmt
'''

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.test]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
  "nextest", "--help",
] }
command = "cargo"
args = [
  "nextest", "run", "--workspace",
  "--status-level", "all", "--test-threads=1",
]

[tasks.clippy-ci]
command = "cargo"
args = ["clippy", "--", "--no-deps", "-Dwarnings"]

[tasks.test-ci]
run_task = "test"
