max_width = 120

# インデントのスペース数
hard_tabs = false
tab_spaces = 4

# 関数の引数リストや構造体のフィールドが長い場合に、ブロック内で改行する
fn_call_width = 60
struct_lit_width = 40
struct_variant_width = 40

# 引数が複数行になる場合にブロックスタイルで表示する
combine_control_expr = false
fn_single_line = false

# 構造体や列挙型のフィールドを揃える
struct_field_align_threshold = 20

# メソッドチェーンが長くなったら改行する
chain_width = 60

# `use` 文をグループ化し、並べ替える
reorder_imports = true
group_imports = "StdExternalCrate"

# `where` 句が長くなったら改行する
where_single_line = false
where_style = "Rfc"

# `match` 式のアームのインデントを統一
match_block_trailing_comma = true
match_arm_blocks = false

# コメントの最大幅
wrap_comments = true
comment_width = 120

# 配列やタプルが長くなったら改行する
array_width = 60

# `use` 文の中で `self`, `super`, `crate` を前に持ってくる
imports_granularity = "Crate"

# 不要な空白の削除を許可する
remove_nested_parens = true
